parameters:
    migrator_jekyll:
        paths_to_remove:
            - 'Gemfile'
            - 'Gemfile.lock'
            - 'Guardfile'
            - '_templates'

        paths_to_move:
            # renames
            '_includes': 'source/_snippets'

            # fnmatch match
            '*.html': 'source/'
            '*.md': 'source/'

            # same
            'favicon.ico': 'source/favicon.ico'
            'favicon.png': 'source/favicon.png'
            '_config.yml': 'source/_config.yml'
            'feed.xml': 'source/feed.xml'
            'Gruntfile.js': 'source/Gruntfile.js'
            'assets': 'source/assets'
            'images': 'source/images'
            '_posts': 'source/_posts'
            '_layouts': 'source/_layouts'
            '_drafts': 'source/_drafts'
            '_data': 'source/_data'
            '_sass': 'source/_sass'
            'CNAME': 'source/CNAME'

        apply_regular_in_paths:
            'source':
                # parameters are accessed directly, without any prefix - see https://regex101.com/r/PvaeHS/1
                '#({%|{{)(.*?\b)(site\.data\.|site\.)#': '$1$2'

                # remove --- --- in the start
                '#^\-\-\-\n\-\-\-\n#m': ''

                # join: to join()
                '#({{\s*tags\s*\|\s*join):(\s*[^|}|]+)#': '$1($2)'

                # strip_html
                '#(.*|\*)strip_html(.*)#': '$1striphtml$2'

                # change include html suffix to twig
                '#({% include )(.*?).html( %})#': "$1'$2.twig'$3"

                # change "remove" to "replace" - @see https://regex101.com/r/iTaipb/2
                '#(\|(\s+)?)(?<filter>remove):\s*(?<value>.*?)\s*(\||}})#': "$1replace($4, '')$5"

                # replace "contains" with "in" - @see https://regex101.com/r/iTaipb/3
                '#({(%|{).*?)\s*(?<value>\w+)\s*contains\s*(?<needle>.*?)(\s)#': '$1 $4 in $3$5'

                '#^(permalink):(\s*(.*?)$\s*)#ms': 'outputPath:$2'

                # replace "assign" with "set"
                '#({%)\s*assign\s*(.*?)#': '$1 set $2'
                '#{% capture (.*?) endcapture %}#': '{% set $1 endset %}'

            source/_posts:
                # remove layout from posts, not needed
                '#^layout: \w+\s+#ms': ''
                '#^(date|date_gmt): (.*?)$\s*#m': ''

services:
    _defaults:
        public: true
        autowire: true

    Symplify\Statie\MigratorJekyll\:
        resource: '../src'
