<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNpGJ3Xx\testsDev7079DebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNpGJ3Xx/testsDev7079DebugProjectContainer.php') {
    touch(__DIR__.'/ContainerNpGJ3Xx.legacy');

    return;
}

if (!\class_exists(testsDev7079DebugProjectContainer::class, false)) {
    \class_alias(\ContainerNpGJ3Xx\testsDev7079DebugProjectContainer::class, testsDev7079DebugProjectContainer::class, false);
}

return new \ContainerNpGJ3Xx\testsDev7079DebugProjectContainer(array(
    'container.build_hash' => 'NpGJ3Xx',
    'container.build_id' => 'c80af215',
    'container.build_time' => 1525301021,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerNpGJ3Xx');
