<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Symplify\PackageBuilder\Parameter\ParameterProvider' shared autowired service.

return $this->services['Symplify\PackageBuilder\Parameter\ParameterProvider'] = new \Symplify\PackageBuilder\Parameter\ParameterProvider($this);
