<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXnlb7N6\testsDev7503DebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXnlb7N6/testsDev7503DebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXnlb7N6.legacy');

    return;
}

if (!\class_exists(testsDev7503DebugProjectContainer::class, false)) {
    \class_alias(\ContainerXnlb7N6\testsDev7503DebugProjectContainer::class, testsDev7503DebugProjectContainer::class, false);
}

return new \ContainerXnlb7N6\testsDev7503DebugProjectContainer(array(
    'container.build_hash' => 'Xnlb7N6',
    'container.build_id' => '2443c043',
    'container.build_time' => 1525301021,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerXnlb7N6');
