<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKXoniVi\testsDev9911DebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKXoniVi/testsDev9911DebugProjectContainer.php') {
    touch(__DIR__.'/ContainerKXoniVi.legacy');

    return;
}

if (!\class_exists(testsDev9911DebugProjectContainer::class, false)) {
    \class_alias(\ContainerKXoniVi\testsDev9911DebugProjectContainer::class, testsDev9911DebugProjectContainer::class, false);
}

return new \ContainerKXoniVi\testsDev9911DebugProjectContainer(array(
    'container.build_hash' => 'KXoniVi',
    'container.build_id' => '820159af',
    'container.build_time' => 1525303879,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerKXoniVi');
