<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerS4wz9tR\testsDev2097DebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerS4wz9tR/testsDev2097DebugProjectContainer.php') {
    touch(__DIR__.'/ContainerS4wz9tR.legacy');

    return;
}

if (!\class_exists(testsDev2097DebugProjectContainer::class, false)) {
    \class_alias(\ContainerS4wz9tR\testsDev2097DebugProjectContainer::class, testsDev2097DebugProjectContainer::class, false);
}

return new \ContainerS4wz9tR\testsDev2097DebugProjectContainer(array(
    'container.build_hash' => 'S4wz9tR',
    'container.build_id' => 'd687a347',
    'container.build_time' => 1525303879,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerS4wz9tR');
